### ISSUE TITLE
Weird sound in LONG sentence

### ISSUE THREAD

**Issue by blx0102** [keonlee9420/Comprehensive-Transformer-TTS#16]
Hi, it's a really nice work!
In my experiment, the speech goes weird after 10s (short sentences are all good). Losses decrese normally, and I checked the predicted dur/pitch/energy, they were all good as well. Only the mel goes weird.
Have you ever encontered this kind of problem in long sentences?

**Comment by keonlee9420** [comment]
Hi @blx0102 , thanks for your attention.

Normally, it happens due to the maximum sequence length of the positional encoding in Transformer blocks of encoder and decoder. So, it would be helpful to increase that number.

**Comment by blx0102** [comment]
@keonlee9420 Thanks! I tried and the speech quality improved a lot!
