### ISSUE TITLE
Voice embeddings: Can VCTK embeddings be used after training on non VCTK data?

### ISSUE THREAD

**Issue by michael-conrad** [keonlee9420/Comprehensive-Transformer-TTS#4]
Voice embeddings: Can VCTK embeddings be used after training on non VCTK data?

I'm looking to see if I can train Cherokee, but then use VCTK voices go speak the Cherokee as donor voices.

Would this be possible?

**Comment by keonlee9420** [comment]
Hi @michael-conrad , unfortunately, I've no idea about that. You may have to fine-tune the pre-trained VCTK model on the target dataset.

**Comment by keonlee9420** [comment]
close due to inactivity.
