### ISSUE TITLE
How about the inference speed of those different block types?

### ISSUE THREAD

**Issue by blx0102** [keonlee9420/Comprehensive-Transformer-TTS#5]
This is really a great project.
There are many types of block in this project, you mentioned the differences of memory cost and the trining speed, could you further introduce the inference speed of every block type?
Thank you!

**Comment by keonlee9420** [comment]
Hi @blx0102 , sorry for the late response. If I have room for that, I will update you with that. But it must be aligned with training time, even for the inference.

**Comment by keonlee9420** [comment]
Close due to inactivity.
